// Two sidebars, one per audience.
//
// Admins and end users were reading past each other's material in a single tree: an end user
// scrolling hit "Restriction rules"; an admin looking for sharing scrolled past "Tasks and
// events". Each track now gets a sidebar that is only about them, and the navbar switches
// between the two.
//
// Both are autogenerated, so adding a page is a file plus a _category_.json position - never
// an edit here.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  features: [{ type: "autogenerated", dirName: "features" }],
  use: [{ type: "autogenerated", dirName: "use" }],
  admin: [{ type: "autogenerated", dirName: "admin" }],
};

module.exports = sidebars;
