// One sidebar per audience.
//
// Admins and end users were reading past each other's material in a single tree: an end user
// scrolling hit "Restriction rules"; an admin looking for sharing scrolled past "Tasks and
// events". Each track now gets a sidebar that is only about them, and the navbar switches
// between the two.
//
// FrontSpin is a fourth track rather than a section of the admin one: it documents an
// integration that is NOT part of the EasyCRM package, so burying it under
// "Administering EasyCRM" would imply every reader has it.
//
// All are autogenerated, so adding a page is a file plus a _category_.json position - never
// an edit here.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  features: [{ type: "autogenerated", dirName: "features" }],
  use: [{ type: "autogenerated", dirName: "use" }],
  admin: [{ type: "autogenerated", dirName: "admin" }],
  api: [{ type: "autogenerated", dirName: "api" }],
  frontspin: [{ type: "autogenerated", dirName: "frontspin" }],
  standardBuild: [{ type: "autogenerated", dirName: "standard-build" }],
};

module.exports = sidebars;
