// One autogenerated sidebar off the docs folder. Each section carries its own
// _category_.json, so adding a page never means editing this file.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [{ type: "autogenerated", dirName: "." }],
};

module.exports = sidebars;
